'use client';

import React, { useState, useEffect } from 'react';
import {
  Plus,
  Users,
  Trophy,
  Star,
  ArrowUpRight,
  Flame,
  Layout,
  TrendingUp,
  Activity,
  Award
} from 'lucide-react';
import { useRouter } from 'next/navigation';
import { apiClient } from '@/core/api/api.client';
import { format } from 'date-fns';
import { es } from 'date-fns/locale';
import { workersService } from '@/features/auth/services/workers.service';

// Dynamic role layout switching
import { useAuth } from '@/core/contexts/AuthContext';
import { MenteeLayout } from '@/features/mentee/components/MenteeLayout';
import { MenteeDashboard } from '@/features/mentee/components/MenteeDashboard';

// 3D Assets generated by IA
const ASSETS_3D = {
  templates: '/assets/3d/templates.png',
  habits: '/assets/3d/habits.png',
  programs: '/assets/3d/programs.png',
  students: '/assets/3d/students.png'
};

export default function DashboardPage() {
  const { user } = useAuth();

  // Track selected coach for the student portal (cached in localStorage)
  const [selectedCoach, setSelectedCoach] = useState<{ id: string; name: string; specialty: string; avatarUrl?: string } | null>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('iter_selected_coach');
      try {
        return saved ? JSON.parse(saved) : null;
      } catch (e) {
        return null;
      }
    }
    return null;
  });

  // Default tab is 'panel' if a coach is already selected, otherwise 'coach'
  const [activeTab, setActiveTab] = useState(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('iter_selected_coach');
      return saved ? 'panel' : 'coach';
    }
    return 'coach';
  });

  // Switch layouts dynamically based on role
  if (user?.role === 'mentee') {
    return (
      <MenteeLayout
        activeTab={activeTab}
        setActiveTab={setActiveTab}
        selectedCoach={selectedCoach}
      >
        <MenteeDashboard
          activeTab={activeTab}
          setActiveTab={setActiveTab}
          selectedCoach={selectedCoach}
          setSelectedCoach={(coach) => {
            setSelectedCoach(coach);
            if (coach) {
              localStorage.setItem('iter_selected_coach', JSON.stringify(coach));
            } else {
              localStorage.removeItem('iter_selected_coach');
            }
          }}
        />
      </MenteeLayout>
    );
  }

  // Fallback to traditional administrative coach dashboard
  return <CoachDashboard />;
}

function CoachDashboard() {
  const { user } = useAuth();
  const router = useRouter();
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchDashboardData = async () => {
      try {
        const [metrics, templates, habits, students, ownerMetrics, staffData] = await Promise.all([
          apiClient.get<any>('/dashboard/metrics'),
          apiClient.get<any[]>('/mentor/programs?isTemplate=true&limit=5'),
          apiClient.get<any[]>('/mentor/programs?type=HABITS&limit=5'),
          apiClient.get<any[]>('/mentor/users/mentees?limit=5'),
          apiClient.get<any>('/mentor/dashboards/owner').catch(() => null),
          workersService.getWorkers({ excludeRole: 'mentee' }).catch(() => ({ items: [], total: 0 }))
        ]);

        setData({ metrics, templates, habits, students, ownerMetrics, staff: staffData.items });
      } catch (err) {
        console.error('Error fetching dashboard data:', err);
      } finally {
        setLoading(false);
      }
    };
    fetchDashboardData();
  }, []);

  if (loading) return (
    <div className="min-h-screen flex items-center justify-center bg-[#F8F9FD]">
      <div className="flex flex-col items-center gap-6">
        <div className="w-20 h-20 border-[6px] border-indigo-50 border-t-indigo-600 rounded-full animate-spin shadow-2xl" />
        <p className="text-[11px] font-black text-slate-400 uppercase tracking-[0.4em] animate-pulse italic">Iniciando Sistemas de Comando...</p>
      </div>
    </div>
  );

  const activeRole = user?.roles?.find((r: any) => r.tenantId === user?.tenantId);
  const isOwner = activeRole?.roleSlug === 'mentor_owner';

  // Incluimos al usuario logueado en la nómina de coaches/staff solo si es el Owner principal
  const allStaff = [...(data?.staff || [])];
  if (isOwner && user && !allStaff.some(s => s.id === user.id)) {
    allStaff.unshift({
      id: user.id,
      firstName: user.firstName || 'Academy',
      lastName: user.lastName || 'Coach',
      email: user.email,
      role: user.role
    });
  }

  const staffWithPerformance = allStaff.map((worker: any) => {
    const perf = (data?.ownerMetrics?.staffPerformance || []).find(
      (p: any) => p.coachId === worker.id
    );
    return {
      ...worker,
      assignedMenteesCount: perf?.assignedMenteesCount || 0,
      completedSessionsCount: perf?.completedSessionsCount || 0,
      pendingReviewsCount: perf?.pendingReviewsCount || 0,
      createdProgramsCount: perf?.createdProgramsCount || 0,
      overallRating: perf?.overallRating || 5
    };
  });

  return (
    <div className="w-full p-4 lg:p-6 space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-1000">

      {/* 1. HEADER & COMMAND SEARCH */}
      <header className="flex flex-col xl:flex-row items-start xl:items-center justify-between gap-6">
        <div>
          <h1 className="text-3xl md:text-4xl font-black text-slate-900 tracking-tighter uppercase leading-none italic">
            Dashboard
          </h1>
        </div>
      </header>

      {/* 2. TACTICAL QUICK ACTIONS */}
      <section className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {[
          { label: 'NUEVO PROGRAMA', icon: Plus, color: 'bg-indigo-600', path: '/dashboard/programs/new' },
          { label: 'GESTIÓN GRUPAL', icon: Users, color: 'bg-slate-900', path: '/dashboard/groups' },
          { label: 'AGENDAR SESIÓN', icon: Star, color: 'bg-amber-500', path: '/dashboard/agenda' },
          { label: 'GAMIFICACIÓN', icon: Trophy, color: 'bg-emerald-600', path: '/dashboard/gamification' }
        ].map((action, i) => (
          <button
            key={i}
            onClick={() => router.push(action.path)}
            className="flex items-center gap-4 p-4 bg-white border border-slate-200 rounded-lg hover:shadow-md hover:border-slate-300 transition-all duration-300 group text-left relative overflow-hidden"
          >
            <div className={`${action.color} w-9 h-9 rounded-md text-white flex items-center justify-center shadow-sm group-hover:scale-105 transition-all duration-300`}>
              <action.icon className="w-4 h-4" />
            </div>
            <span className="text-[9px] font-black text-slate-900 uppercase tracking-[0.15em] italic">{action.label}</span>
            <div className="absolute top-0 right-0 p-3 opacity-0 group-hover:opacity-100 transition-opacity">
              <ArrowUpRight className="w-3.5 h-3.5 text-indigo-600" />
            </div>
          </button>
        ))}
      </section>

      {/* 3. INDUSTRIAL HUB STATS (GYM SPECIFIC) */}
      <section className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        {[
          { name: 'ESTUDIANTES ASIGNADOS', qty: data?.ownerMetrics?.totalMentees || 0, unit: 'ACTIVOS', img: ASSETS_3D.students, color: 'text-sky-500', bg: 'bg-sky-50/50', path: '/dashboard/clients' },
          { name: 'ENTRENADORES ACTUANTES', qty: data?.ownerMetrics?.activeCoachesCount || 0, unit: 'NÓMINA', img: ASSETS_3D.templates, color: 'text-indigo-600', bg: 'bg-indigo-50/50', path: '/dashboard/staff' },
          { name: 'PROGRAMAS DEL GYM', qty: data?.ownerMetrics?.totalPrograms || 0, unit: 'DESPLIEGUES', img: ASSETS_3D.programs, color: 'text-amber-500', bg: 'bg-amber-50/50', path: '/dashboard/programs' },
          { name: 'HÁBITOS Y PROTOCOLOS', qty: data?.habits?.length || 0, unit: 'SISTEMAS', img: ASSETS_3D.habits, color: 'text-emerald-600', bg: 'bg-emerald-50/50', path: '/dashboard/habits' }
        ].map((stat, i) => (
          <div
            key={i}
            onClick={() => router.push(stat.path)}
            className="glass-card bg-white/70 backdrop-blur-xl rounded-lg p-5 border border-slate-200 shadow-sm hover:shadow-md hover:border-slate-300 transition-all duration-500 cursor-pointer group relative overflow-hidden flex flex-col items-center text-center"
          >
            <div className="absolute -right-6 -bottom-6 w-32 h-32 bg-white/50 rounded-full group-hover:scale-120 transition-transform duration-700 opacity-20" />

            <div className="w-16 h-16 mb-3 group-hover:scale-105 transition-transform duration-500 drop-shadow-[0_10px_25px_rgba(0,0,0,0.03)] relative z-10">
              <img src={stat.img} alt={stat.name} className="w-full h-full object-contain" />
            </div>

            <div className="relative z-10 space-y-1">
              <p className="text-[8px] font-black text-slate-900 uppercase tracking-[0.25em] italic opacity-60">{stat.name}</p>
              <div className="flex items-baseline justify-center gap-1.5">
                <h3 className={`text-3xl font-black tracking-tighter italic ${stat.color}`}>{stat.qty}</h3>
                <span className="text-[7px] font-black text-slate-800 uppercase tracking-widest italic">{stat.unit}</span>
              </div>
            </div>
          </div>
        ))}
      </section>

      {/* 4. TACTICAL DATA DOSSIERS */}
      <section className="grid grid-cols-1 xl:grid-cols-12 gap-6">

        {/* Templates Monitor */}
        <div className="xl:col-span-7 glass-card bg-white/70 backdrop-blur-xl rounded-lg border border-slate-200 shadow-sm overflow-hidden group">
          <div className="p-4 border-b border-slate-100 flex items-center justify-between bg-slate-50/50">
            <div className="flex items-center gap-3">
              <div className="w-1.5 h-4 bg-indigo-500 rounded-full shadow-sm" />
              <h3 className="text-sm font-black text-slate-900 uppercase tracking-tighter italic leading-none">Últimos Protocolos</h3>
            </div>
            <button
              onClick={() => router.push('/dashboard/programs')}
              className="px-3 py-1.5 bg-white text-[8px] font-black text-indigo-600 uppercase tracking-widest rounded-md hover:bg-slate-900 hover:text-white transition-all italic border border-slate-200"
            >
              Ver Archivo
            </button>
          </div>
          <div className="overflow-x-auto p-2">
            <table className="w-full text-left">
              <thead>
                <tr className="text-[8px] font-black text-slate-400 uppercase tracking-[0.2em] italic border-b border-slate-100">
                  <th className="px-4 py-3">IDENTIFICADOR</th>
                  <th className="px-4 py-3">TIPO</th>
                  <th className="px-4 py-3 text-right">ACCESO</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100/50">
                {Array.isArray(data?.templates) && data.templates.slice(0, 5).map((item: any) => (
                  <tr key={item.id} className="group/row hover:bg-indigo-50/30 transition-all duration-500">
                    <td className="px-4 py-3">
                      <div className="flex flex-col gap-0.5">
                        <span className="font-black text-slate-900 uppercase text-xs tracking-tight italic group-hover/row:text-indigo-600 transition-colors">{item.name}</span>
                        <span className="text-[7px] text-slate-300 font-black uppercase tracking-widest">ID: #SYS-{item.id.slice(0, 8)}</span>
                      </div>
                    </td>
                    <td className="px-4 py-3">
                      <div className="flex items-center gap-1.5 px-3 py-1 bg-slate-100 text-slate-500 rounded-md text-[7px] font-black uppercase tracking-widest italic group-hover/row:bg-white group-hover/row:text-slate-700 transition-all border border-transparent group-hover/row:border-slate-100 shadow-sm w-fit">
                        <Layout className="w-2.5 h-2.5" />
                        {item.type}
                      </div>
                    </td>
                    <td className="px-4 py-3 text-right">
                      <button
                        onClick={() => router.push(`/dashboard/programs/${item.id}`)}
                        className="w-7 h-7 bg-white border border-slate-200 rounded-md flex items-center justify-center text-slate-300 hover:text-indigo-600 hover:border-indigo-500 transition-all shadow-sm group-hover/row:scale-105 active:scale-95 group/btn"
                      >
                        <ArrowUpRight className="w-3.5 h-3.5 group-hover/btn:translate-x-0.5 group-hover/btn:-translate-y-0.5 transition-transform" />
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Behavior Pulso Monitor */}
        <div className="xl:col-span-5 flex flex-col gap-6">
          {/* Racha Global - Oculto temporalmente */}

          <div className="glass-card bg-white/70 backdrop-blur-xl p-5 rounded-lg border border-slate-200 shadow-sm relative overflow-hidden group">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-xs font-black text-slate-900 uppercase tracking-tighter italic flex items-center gap-2">
                <Users className="w-4 h-4 text-indigo-600" />
                Nuevos Ingresos
              </h3>
              <button className="text-slate-300 hover:text-indigo-600 transition-colors"><Plus className="w-3.5 h-3.5" /></button>
            </div>
            <div className="space-y-2">
              {Array.isArray(data?.students) && data.students.slice(0, 4).map((student: any) => (
                <div key={student.id} className="flex items-center justify-between p-2 hover:bg-white rounded-md border border-transparent hover:border-slate-100 transition-all duration-300 group/item hover:shadow-sm">
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 rounded-md bg-slate-900 text-white flex items-center justify-center font-black text-[9px] shadow-sm group-hover/item:rotate-6 transition-transform">
                      {student.name?.charAt(0).toUpperCase() || 'U'}
                    </div>
                    <div>
                      <p className="text-[10px] font-black text-slate-900 uppercase tracking-tight italic">{student.name}</p>
                      <p className="text-[7px] text-slate-400 font-black uppercase tracking-widest opacity-60 italic">
                        {student.createdAt ? format(new Date(student.createdAt), 'dd MMM yyyy') : 'REGISTRO RECIENTE'}
                      </p>
                    </div>
                  </div>
                  <ArrowUpRight className="w-3.5 h-3.5 text-slate-200 group-hover/item:text-indigo-600 group-hover/item:translate-x-0.5 group-hover/item:-translate-y-0.5 transition-all" />
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* 5. TACTICAL STAFF PERFORMANCE DOSSIER (OWNER ONLY) */}
      {isOwner && (
        <section className="glass-card bg-white/70 backdrop-blur-xl rounded-lg border border-slate-200 shadow-sm overflow-hidden group">
          <div className="p-4 border-b border-slate-100 flex items-center justify-between bg-slate-50/50">
            <div className="flex items-center gap-3">
              <div className="w-1.5 h-4 bg-indigo-500 rounded-full shadow-sm" />
              <h3 className="text-sm font-black text-slate-900 uppercase tracking-tighter italic leading-none">Rendimiento de Coaches / Staff</h3>
            </div>
            <button
              onClick={() => router.push('/dashboard/staff')}
              className="px-3 py-1.5 bg-white text-[8px] font-black text-indigo-600 uppercase tracking-widest rounded-md hover:bg-slate-900 hover:text-white transition-all italic border border-slate-200"
            >
              Gestionar Staff
            </button>
          </div>
          <div className="overflow-x-auto p-2">
            <table className="w-full text-left">
              <thead>
                <tr className="text-[8px] font-black text-slate-400 uppercase tracking-[0.2em] italic border-b border-slate-100">
                  <th className="px-4 py-3">ENTRENADOR</th>
                  <th className="px-4 py-3">ESTUDIANTES ASIGNADOS</th>
                  <th className="px-4 py-3">SESIONES DICTADAS</th>
                  <th className="px-4 py-3">REVISIONES PENDIENTES</th>
                  <th className="px-4 py-3">PROGRAMAS CREADOS</th>
                  <th className="px-4 py-3 text-right">DESEMPEÑO</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100/50">
                {staffWithPerformance.length === 0 ? (
                  <tr>
                    <td colSpan={6} className="px-4 py-8 text-center text-slate-400 font-black text-[9px] uppercase tracking-widest italic">
                      No se han registrado entrenadores en esta sede operativa.
                    </td>
                  </tr>
                ) : (
                  staffWithPerformance.map((worker: any) => (
                    <tr key={worker.id} className="group/row hover:bg-indigo-50/30 transition-all duration-500">
                      <td className="px-4 py-3">
                        <div className="flex items-center gap-3">
                          <div className="w-8 h-8 rounded-md bg-slate-900 text-white flex items-center justify-center font-black text-[10px] shadow-sm group-hover/row:scale-105 transition-all">
                            {worker.firstName?.charAt(0).toUpperCase() || 'C'}
                          </div>
                          <div className="flex flex-col gap-0.5">
                            <span className="font-black text-slate-900 uppercase text-xs tracking-tight italic group-hover/row:text-indigo-600 transition-colors">
                              {worker.firstName} {worker.lastName}
                            </span>
                            <span className="text-[7px] text-slate-400 font-black uppercase tracking-widest">{worker.email}</span>
                          </div>
                        </div>
                      </td>
                      <td className="px-4 py-3">
                        <div className="flex items-center gap-1 text-slate-700 font-black text-xs italic">
                          <Users className="w-3.5 h-3.5 text-sky-500" />
                          {worker.assignedMenteesCount} <span className="text-[7px] text-slate-400 uppercase tracking-widest not-italic font-black">ESTUDIANTES</span>
                        </div>
                      </td>
                      <td className="px-4 py-3">
                        <div className="flex items-center gap-1 text-slate-700 font-black text-xs italic">
                          <Activity className="w-3.5 h-3.5 text-emerald-500" />
                          {worker.completedSessionsCount} <span className="text-[7px] text-slate-400 uppercase tracking-widest not-italic font-black">COMPLETADAS</span>
                        </div>
                      </td>
                      <td className="px-4 py-3">
                        <div className={`flex items-center gap-1 font-black text-xs italic ${worker.pendingReviewsCount > 0 ? 'text-amber-500 animate-pulse' : 'text-slate-400'}`}>
                          <TrendingUp className="w-3.5 h-3.5" />
                          {worker.pendingReviewsCount} <span className="text-[7px] text-slate-400 uppercase tracking-widest not-italic font-black">EN COLA</span>
                        </div>
                      </td>
                      <td className="px-4 py-3">
                        <div className="flex items-center gap-1 text-slate-700 font-black text-xs italic">
                          <Layout className="w-3.5 h-3.5 text-indigo-500" />
                          {worker.createdProgramsCount} <span className="text-[7px] text-slate-400 uppercase tracking-widest not-italic font-black">PROTOCOLOS</span>
                        </div>
                      </td>
                      <td className="px-4 py-3 text-right">
                        <div className="flex items-center justify-end gap-0.5 text-amber-500">
                          {Array.from({ length: 5 }).map((_, idx) => (
                            <Star key={idx} className="w-3 h-3 fill-current animate-pulse" />
                          ))}
                        </div>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </section>
      )}
    </div>
  );
}
